#!/bin/bash

tb() {
	if (command -v py) > 0;
	then

		py "$(dirname "${BASH_SOURCE[0]}")/true-blame.py" "$@"
	elif (command -v python) > 0;
	then
		python "$(dirname "${BASH_SOURCE[0]}")/true-blame.py" "$@"
	fi
}

tb "$@"